# Generated by Django 6.0.3 on 2026-03-18 13:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('program_tag', models.CharField(blank=True, help_text='Tag used to filter gallery images for this program (e.g. cybersecurity)', max_length=100)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('carousel', 3), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Image Carousel'}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('text', 4), ('link', 4)]], {})})),
            ],
            options={
                'verbose_name': 'Program Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Programs Index Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
