# Generated by Django 6.0.3 on 2026-03-18 13:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('carousel', 4), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Image Carousel'}), 5: ('wagtail.blocks.StructBlock', [[('text', 1), ('link', 1)]], {})}),
        ),
    ]
