# Generated by Django 6.0.3 on 2026-04-14 08:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_programs', '0002_alter_programpage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='audience',
            field=wagtail.fields.RichTextField(blank=True, help_text='Who this program supports. Shown in a dedicated "Who it supports" section.'),
        ),
        migrations.AddField(
            model_name='programpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='programpage',
            name='gallery_note',
            field=models.CharField(blank=True, help_text='Optional "See more photos" callout text linking to the gallery.', max_length=300),
        ),
        migrations.AddField(
            model_name='programpage',
            name='primary_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='programpage',
            name='primary_cta_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='programpage',
            name='schedule',
            field=models.CharField(blank=True, help_text='When the program runs, e.g. "Every Thursday 10am–12pm".', max_length=200),
        ),
        migrations.AddField(
            model_name='programpage',
            name='summary',
            field=models.CharField(blank=True, help_text='Short one-to-two sentence summary shown on program cards and in the overview grid.', max_length=300),
        ),
        migrations.AddField(
            model_name='programpage',
            name='venue',
            field=models.CharField(blank=True, help_text='Where the program is held.', max_length=200),
        ),
        migrations.AddField(
            model_name='programsindexpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Optional header image for the Programs overview page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='programsindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Overview introduction shown at the top of the Programs page.'),
        ),
    ]
