# Generated by Django 6.0.3 on 2026-04-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_programs', '0003_programpage_audience_programpage_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='category',
            field=models.CharField(blank=True, choices=[('seniors', 'Seniors'), ('children', 'Children & Families'), ('women', 'Women & Families'), ('settlement', 'Settlement'), ('digital', 'Digital Safety'), ('social', 'Social Support')], help_text='Program category shown as an eyebrow label on the overview card.', max_length=50),
        ),
    ]
