# Generated by Django 6.0.3 on 2026-04-27 16:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_programs', '0005_programpage_outcomes_alter_programpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Program-specific contact email (optional).', max_length=254),
        ),
        migrations.AddField(
            model_name='programpage',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Program-specific contact person (optional).', max_length=120),
        ),
        migrations.AddField(
            model_name='programpage',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Program-specific contact phone (optional).', max_length=40),
        ),
        migrations.AddField(
            model_name='programpage',
            name='cost',
            field=models.CharField(blank=True, help_text='Cost to participants, e.g. "Free" or "By referral". Shown as a quick-scan pill.', max_length=100),
        ),
        migrations.AddField(
            model_name='programpage',
            name='cta_heading',
            field=models.CharField(blank=True, help_text='Sidebar CTA card heading. Default: "Want to support this program?"', max_length=120),
        ),
        migrations.AddField(
            model_name='programpage',
            name='language',
            field=models.CharField(blank=True, help_text='Language(s) the program is delivered in, e.g. "Khmer and English".', max_length=120),
        ),
        migrations.AlterField(
            model_name='programpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('highlight_box', 6), ('photo_grid', 10), ('button', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "90+" or "$3,000"', 'label': 'Stat or key number'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "participants each week"', 'label': 'Label'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Supporting text (optional)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('stat', 3), ('label', 4), ('description', 5)]], {'label': 'Highlight Box'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Caption (optional)', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 7), ('caption', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Photo Grid'}), 11: ('wagtail.blocks.StructBlock', [[('text', 1), ('link', 1)]], {})}),
        ),
    ]
