# Generated by Django 6.0.3 on 2026-05-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_programs', '0006_programpage_contact_email_programpage_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name shown on cards and the program page, e.g. "Seniors" or "Women & Families".', max_length=80)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first in filter chips. Use 0, 10, 20 to leave room for reordering.')),
            ],
            options={
                'verbose_name': 'Program Category',
                'verbose_name_plural': 'Program Categories',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='programpage',
            name='category',
            field=models.CharField(blank=True, choices=[('seniors', 'Seniors'), ('children', 'Children & Families'), ('women', 'Women & Families'), ('settlement', 'Settlement'), ('digital', 'Digital Safety'), ('social', 'Social Support')], help_text='Legacy fixed category. New programs should use "Category (snippet)" below instead.', max_length=50),
        ),
        migrations.AddField(
            model_name='programpage',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Pick a category from the list managed under Snippets → Program Categories. If set, this overrides the legacy category field above.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='a_programs.programcategory', verbose_name='Category'),
        ),
    ]
