# Generated by Django 6.0.3 on 2026-05-18

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_translation_keys(apps, schema_editor):
    """Assign a unique UUID to each existing ProgramCategory row.

    AddField with default=uuid.uuid4 sets the same value for every row on
    PostgreSQL, so we backfill row-by-row before adding the unique constraint.
    """
    ProgramCategory = apps.get_model('a_programs', 'ProgramCategory')
    for obj in ProgramCategory.objects.all():
        obj.translation_key = uuid.uuid4()
        obj.save(update_fields=['translation_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('a_programs', '0007_programcategory_alter_programpage_category_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcategory',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programcategory',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(populate_translation_keys, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='programcategory',
            unique_together={('translation_key', 'locale')},
        ),
    ]
