# Generated by Django 6.0.3 on 2026-04-01 22:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
                ('categories', wagtail.fields.StreamField([('category', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('is_active', 1)]], {})})),
                ('event_cards', wagtail.fields.StreamField([('event', 6)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'View Details', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('date', 0), ('title', 1), ('location', 2), ('description', 3), ('cta_text', 4), ('cta_link', 5)]], {})})),
                ('featured_label', models.CharField(blank=True, max_length=80)),
                ('featured_title', models.CharField(blank=True, max_length=120)),
                ('featured_date_text', models.CharField(blank=True, max_length=120)),
                ('featured_time_text', models.CharField(blank=True, max_length=120)),
                ('featured_venue_text', models.CharField(blank=True, max_length=120)),
                ('featured_entry_text', models.CharField(blank=True, max_length=120)),
                ('featured_details', wagtail.fields.StreamField([('detail', 0)], blank=True, block_lookup={0: ('a_events.models.FeaturedDetailBlock', (), {})})),
                ('featured_cta_text', models.CharField(blank=True, max_length=80)),
                ('featured_cta_link', models.URLField(blank=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('featured_map_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
