# Generated by Django 6.0.3 on 2026-04-13 09:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='featured_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='event_cards',
            field=wagtail.fields.StreamField([('event', 6)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'View Details', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('date', 0), ('title', 1), ('category', 2), ('location', 2), ('description', 3), ('image', 4), ('cta_text', 5), ('cta_link', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='featured_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
