# Generated by Django 6.0.3 on 2026-04-13 10:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_events', '0002_eventspage_featured_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspage',
            name='event_cards',
            field=wagtail.fields.StreamField([('event', 6)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'View Details', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('date', 0), ('title', 1), ('category', 2), ('location', 2), ('description', 3), ('image', 4), ('cta_text', 5), ('cta_link', 2)]], {})}),
        ),
    ]
