# Generated by Django 6.0.3 on 2026-04-28 05:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_events', '0003_alter_eventspage_event_cards'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(blank=True, choices=[('cultural', 'Cultural'), ('settlement', 'Settlement'), ('community', 'Community Support'), ('workshop', 'Workshop'), ('information', 'Information Session'), ('social', 'Social')], help_text='Category shown on event cards and the detail page.', max_length=60)),
                ('is_featured', models.BooleanField(default=False, help_text='Pin this event as the featured event on the Events index page.')),
                ('event_date', models.DateField(blank=True, help_text='Leave blank if the date is TBC.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional: end date for multi-day events.', null=True)),
                ('event_time', models.CharField(blank=True, help_text='e.g. "10am – 12pm"', max_length=120)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, help_text='Full address shown on the detail page.', max_length=300)),
                ('cost', models.CharField(blank=True, help_text='e.g. "Free" or "By registration".', max_length=100)),
                ('language', models.CharField(blank=True, help_text='e.g. "Khmer and English".', max_length=100)),
                ('summary', models.CharField(blank=True, help_text='Short summary shown on event cards (auto-generated from body if blank).', max_length=280)),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Full event description shown on the detail page.')),
                ('registration_link', models.CharField(blank=True, help_text='External RSVP or registration URL.', max_length=255)),
                ('registration_text', models.CharField(blank=True, help_text='Registration button label, e.g. "Register Now" or "RSVP by 30 June".', max_length=80)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Event Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
