# Generated by Django 6.0.3 on 2026-04-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_events', '0004_eventpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='address',
            field=models.CharField(blank=True, help_text='Full street address, e.g. "1 Smith St, Bonnyrigg NSW 2177". Shown below the venue name.', max_length=300),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='cost',
            field=models.CharField(blank=True, help_text='e.g. "Free", "By registration" or "$5 per person". Leave blank to hide this field.', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_time',
            field=models.CharField(blank=True, help_text='e.g. "10am – 12pm" or "2:00pm – 4:30pm".', max_length=120),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Tick to pin this event as the featured spotlight on the Events page. Only one event should be featured at a time. If none are ticked, the next upcoming event is shown automatically.'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='venue',
            field=models.CharField(blank=True, help_text='Venue name, e.g. "Bonnyrigg Heights Community Centre".', max_length=200),
        ),
    ]
