# Generated by Django 6.0.3 on 2026-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_events', '0005_alter_eventpage_address_alter_eventpage_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventspage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='eventspage',
            name='event_cards',
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='intro',
            field=models.TextField(blank=True, help_text='Intro paragraph shown under the page title.'),
        ),
    ]
