# Generated by Django 6.0.3 on 2026-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_events', '0009_remove_eventspage_eyebrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspage',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/cambodianwelfare', help_text='Facebook page URL for the button.'),
        ),
    ]
