# Generated by Django 6.0.3 on 2026-04-01 12:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'About Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 3), ('carousel', 4), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Image Carousel'}), 5: ('wagtail.blocks.StructBlock', [[('text', 1), ('link', 1)]], {})})),
            ],
            options={
                'verbose_name': 'About Section Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
