# Generated by Django 6.0.3 on 2026-04-01 12:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0002_aboutindexpage_aboutsectionpage_delete_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 3), ('carousel', 4), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Image Carousel'}), 5: ('wagtail.blocks.StructBlock', [[('text', 1), ('link', 1)]], {})}),
        ),
    ]
