# Generated by Django 6.0.3 on 2026-04-01 12:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0003_aboutindexpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 3), ('image_text', 4), ('carousel', 5), ('button', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('image', 3), ('text', 2)]], {'label': 'Image with Text'}), 5: ('wagtail.blocks.ListBlock', (3,), {'label': 'Image Carousel'}), 6: ('wagtail.blocks.StructBlock', [[('text', 1), ('link', 1)]], {})}),
        ),
    ]
