# Generated by Django 6.0.3 on 2026-04-01 13:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0004_alter_aboutindexpage_body'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('directors', wagtail.fields.StreamField([('director', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('role', 1)]], {'label': 'Director'})})),
            ],
            options={
                'verbose_name': 'Board of Directors Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
