# Generated by Django 6.0.3 on 2026-04-06 02:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0005_boardpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('staff_members', wagtail.fields.StreamField([('staff_member', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional program or area of responsibility.', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('role', 1), ('working_hours', 2), ('focus', 3)]], {'label': 'Staff Member'})})),
            ],
            options={
                'verbose_name': 'Staff Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
