# Generated by Django 6.0.3 on 2026-04-13 09:18

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0006_staffpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsectionpage',
            name='feature_items',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional short icon label.', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('eyebrow', 2), ('icon', 3)]], {})}),
        ),
        migrations.AddField(
            model_name='aboutsectionpage',
            name='section_kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('history', 'History'), ('vision', 'Vision'), ('mission', 'Mission'), ('objectives', 'Objectives')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutsectionpage',
            name='stats',
            field=wagtail.fields.StreamField([('stat', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 0), ('description', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='aboutsectionpage',
            name='timeline_items',
            field=wagtail.fields.StreamField([('milestone', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('year', 0), ('title', 1), ('description', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='boardpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='boardpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='boardpage',
            name='primary_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='boardpage',
            name='primary_cta_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='boardpage',
            name='secondary_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='boardpage',
            name='secondary_cta_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='boardpage',
            name='story_heading',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='boardpage',
            name='story_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='primary_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='primary_cta_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='secondary_cta_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='secondary_cta_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='aboutsectionpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 3), ('image_text', 4), ('carousel', 5), ('button', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('image', 3), ('text', 2)]], {'label': 'Image with Text'}), 5: ('wagtail.blocks.ListBlock', (3,), {'label': 'Image Carousel'}), 6: ('wagtail.blocks.StructBlock', [[('text', 1), ('link', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='boardpage',
            name='directors',
            field=wagtail.fields.StreamField([('director', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('role', 1), ('bio', 2)]], {'label': 'Director'})}),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='staff_members',
            field=wagtail.fields.StreamField([('staff_member', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional team grouping such as Operations or Seniors Program.', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional program or area of responsibility.', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('role', 1), ('team', 2), ('description', 3), ('working_hours', 4), ('focus', 5)]], {'label': 'Staff Member'})}),
        ),
    ]
