# Generated by Django 6.0.3 on 2026-04-28 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0009_add_panhary_soeu_board_member'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Optional image shown beside the Who We Are page hero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
