# Generated by Django 6.0.3 on 2026-04-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0010_aboutindexpage_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsectionpage',
            name='section_kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('history', 'History'), ('vision', 'Vision'), ('mission', 'Mission'), ('objectives', 'Objectives')], default='standard', help_text='Controls the page layout. History = timeline of milestones. Vision/Mission = statement layout. Objectives = structured list. Standard = flexible content.', max_length=20),
        ),
    ]
