# Generated by Django 6.0.3 on 2026-05-12 12:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0011_alter_aboutsectionpage_section_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardpage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='boardpage',
            name='story_heading',
        ),
        migrations.RemoveField(
            model_name='boardpage',
            name='story_text',
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='staff_members',
            field=wagtail.fields.StreamField([('staff_member', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('operations', 'Operations & Leadership'), ('settlement', 'Settlement & Casework'), ('seniors', 'Seniors Program'), ('women', 'Women & Family Support'), ('children', 'Children & Youth'), ('outreach', 'Community Outreach'), ('admin', 'Administration & Finance'), ('volunteers', 'Volunteers & Interns')], 'help_text': 'Select the team this person belongs to. Staff with the same team are grouped together on the page.', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional program or area of responsibility.', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('role', 1), ('team', 2), ('description', 3), ('working_hours', 4), ('focus', 5)]], {'label': 'Staff Member'})}),
        ),
    ]
