# Generated by Django 6.0.3 on 2026-05-12 12:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0012_remove_boardpage_featured_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question, e.g. "Are donations tax-deductible?"', max_length=300)),
                ('answer', wagtail.fields.RichTextField(help_text='The answer. Supports basic formatting and links.')),
                ('category', models.CharField(choices=[('general', 'General'), ('programs', 'Programs'), ('donate', 'Donations'), ('volunteer', 'Volunteering'), ('events', 'Events'), ('contact', 'Contact')], default='general', help_text='Used to group FAQs and decide which pages they appear on. "General" FAQs may appear on the homepage. "Donations" FAQs appear on the Donate page. All FAQs appear on the main FAQ page.', max_length=20)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first within their category. Use 0, 10, 20 to leave room for reordering.')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Tick to feature this FAQ on the homepage (up to 4 are shown).')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'sort_order', 'question'],
            },
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='additional_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Supporting paragraphs shown in the "Community-led support" section. Separate paragraphs are split automatically.'),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='page_heading',
            field=models.CharField(blank=True, help_text='Main heading shown at the top of the Who We Are page.', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutindexpage',
            name='page_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Intro paragraph shown directly under the page heading.'),
        ),
        migrations.AlterField(
            model_name='aboutindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 3), ('image_text', 4), ('carousel', 5), ('button', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('image', 3), ('text', 2)]], {'label': 'Image with Text'}), 5: ('wagtail.blocks.ListBlock', (3,), {'label': 'Image Carousel'}), 6: ('wagtail.blocks.StructBlock', [[('text', 1), ('link', 1)]], {})}, help_text='Optional flexible content blocks. Use only if you need richer layouts than the fields above offer.'),
        ),
        migrations.AlterField(
            model_name='aboutindexpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Large image shown below the hero. Landscape orientation works best.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='faqs',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}, help_text='Legacy local FAQs. New FAQs should be added under Snippets → FAQs so they can be reused across pages.'),
        ),
    ]
