# Generated by Django 6.0.3 on 2026-05-18

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_translation_keys(apps, schema_editor):
    """Assign a unique UUID to each existing FAQ row.

    AddField with default=uuid.uuid4 sets the same value for every row on
    PostgreSQL, so we backfill row-by-row before adding the unique constraint.
    """
    FAQ = apps.get_model('a_about', 'FAQ')
    for obj in FAQ.objects.all():
        obj.translation_key = uuid.uuid4()
        obj.save(update_fields=['translation_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('a_about', '0013_faq_aboutindexpage_additional_text_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='locale',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(populate_translation_keys, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='faq',
            unique_together={('translation_key', 'locale')},
        ),
    ]
