# Generated by Django 6.0.3 on 2026-04-28 06:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def seed_resource_content(apps, schema_editor):
    ResourcesPage = apps.get_model('a_resources', 'ResourcesPage')
    AnnualReport = apps.get_model('a_resources', 'AnnualReport')
    CommunityPublication = apps.get_model('a_resources', 'CommunityPublication')
    UsefulLink = apps.get_model('a_resources', 'UsefulLink')

    page = ResourcesPage.objects.filter(slug='resources').first()
    if not page:
        return

    annual_reports = [
        (2025, 'https://www.cambodianwelfare.org.au/_files/ugd/7351f5_7d2cae57d3f246b891834940649ceb1c.pdf'),
        (2024, 'https://www.cambodianwelfare.org.au/_files/ugd/7351f5_dc4f7c91e7fe4ba3a3c6d91d1fe627b9.pdf'),
        (2023, 'https://www.cambodianwelfare.org.au/_files/ugd/7351f5_3e2658d5c3af4fc7bc262361127a4cc1.pdf'),
        (2022, 'https://www.cambodianwelfare.org.au/_files/ugd/7351f5_ab40fc73de854318a5fd301650299de6.pdf'),
        (2021, 'https://www.cambodianwelfare.org.au/_files/ugd/7351f5_1cd4c7e8ffe14835a65232aea1ecb73f.pdf'),
        (2020, 'https://www.cambodianwelfare.org.au/_files/ugd/77d59b_e8bf0de5ef9a49b1801412d3caa553c8.pdf'),
        (2019, 'https://www.cambodianwelfare.org.au/_files/ugd/77d59b_e9135d75cd5242f6a8ea639941d33d67.pdf'),
        (2010, 'https://www.cambodianwelfare.org.au/_files/ugd/77d59b_b05009f9dd3644b78445833d11c114fe.pdf'),
        (2009, 'https://www.cambodianwelfare.org.au/_files/ugd/7351f5_e6897379ee674368964b69dae3438905.pdf'),
    ]
    for sort_order, (year, url) in enumerate(annual_reports):
        report = AnnualReport.objects.filter(page=page, year=year).first()
        if not report:
            AnnualReport.objects.create(page=page, year=year, url=url, sort_order=sort_order)
        elif not report.url:
            report.url = url
            report.sort_order = sort_order
            report.save(update_fields=['url', 'sort_order'])

    publications = [
        ('Digital Security', 'Cybersecurity Community Forum', 'https://www.cambodianwelfare.org.au/_files/ugd/77d59b_44bcdf6745a8437087695e930b00e8aa.pdf'),
        ('Institutional Advocacy', 'State Conference 2003', 'https://www.cambodianwelfare.org.au/_files/ugd/77d59b_8f2d9d76009d45aaa0637f4b35fd867b.pdf'),
        ('Health & Culture', 'Khmer Culture and Attitude Towards Health 2010', 'https://www.cambodianwelfare.org.au/_files/ugd/77d59b_86d50b6409964fa79827828ff71fe867.pdf'),
        ('Archive Conference', 'State Conference 1998', 'https://www.cambodianwelfare.org.au/_files/ugd/77d59b_77e071e2f4964de4a12b3917973beea2.pdf'),
        ('Cultural History', 'Cambodian Culture & Customs Seminar', 'https://www.cambodianwelfare.org.au/_files/ugd/77d59b_7c478cb30bf746cdba958c25e8a5b153.pdf'),
        ('Social History', 'Settlement of People from Cambodia', 'https://www.cambodianwelfare.org.au/_files/ugd/7351f5_adda05a424074f99897e2220450e2bc8.pdf'),
        ('Current Services', 'SETS Brochure', ''),
    ]
    for sort_order, (category, title, url) in enumerate(publications):
        publication = CommunityPublication.objects.filter(page=page, title=title).first()
        if not publication:
            CommunityPublication.objects.create(
                page=page,
                title=title,
                category=category,
                url=url,
                sort_order=sort_order,
            )
        elif not publication.url and url:
            publication.url = url
            publication.category = category
            publication.sort_order = sort_order
            publication.save(update_fields=['url', 'category', 'sort_order'])

    useful_links = [
        ('Government', 'Royal Embassy of Cambodia in Canberra', 'https://www.embassyofcambodia.org.au/', 'Cambodian embassy information and consular services in Australia.'),
        ('Language', 'Khmer Fonts', 'https://www.cambodia.org/fonts/', 'Khmer font resources for reading and writing Khmer text.'),
        ('Support Directory', 'Ask Izzy', 'https://askizzy.org.au/', 'A national directory for housing, food, health, counselling and support services.'),
        ('Legal Help', 'LawAccess NSW', 'https://www.lawaccess.nsw.gov.au/', 'Free legal information, referrals and guidance for people in NSW.'),
        ('Legal Help', 'Legal Aid NSW', 'https://www.legalaid.nsw.gov.au/', 'Legal information, advice and support services for eligible NSW residents.'),
        ('Consumer Rights', 'NSW Fair Trading', 'https://www.fairtrading.nsw.gov.au/', 'Consumer, renting, strata, business and fair trading information.'),
        ('Complaints', 'NSW Ombudsman', 'https://www.ombo.nsw.gov.au/', 'Independent handling of complaints about NSW public agencies and services.'),
        ('Complaints', 'Commonwealth Ombudsman', 'https://www.ombudsman.gov.au/', 'Complaints and information about Australian Government agencies.'),
        ('Complaints', 'Energy & Water Ombudsman NSW', 'https://www.ewon.com.au/', 'Free dispute resolution for electricity, gas and water complaints in NSW.'),
        ('Complaints', 'Telecommunications Industry Ombudsman', 'https://www.tio.com.au/', 'Free complaint handling for phone and internet service issues.'),
        ('Language Services', 'NAATI', 'https://www.naati.com.au/', 'Certification information for translators and interpreters in Australia.'),
        ('Translation', 'Google Translate', 'https://translate.google.com/', 'Quick online translation tool for general understanding.'),
        ('Government', 'Department of Social Services', 'https://www.dss.gov.au/', 'Australian Government social policy, grants and community support information.'),
        ('Government', 'Services Australia', 'https://www.servicesaustralia.gov.au/', 'Centrelink, Medicare and government payment information.'),
        ('Aged Care', 'My Aged Care', 'https://www.myagedcare.gov.au/', 'Australian Government aged care information, assessments and service pathways.'),
    ]
    for sort_order, (category, title, url, description) in enumerate(useful_links):
        if UsefulLink.objects.filter(page=page, title=title).exists():
            continue
        UsefulLink.objects.create(
            page=page,
            title=title,
            category=category,
            url=url,
            description=description,
            sort_order=sort_order,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('a_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDownloadLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('resource_type', models.CharField(choices=[('annual-report', 'Annual Report'), ('publication', 'Community Publication'), ('useful-link', 'Useful Link')], max_length=40)),
                ('resource_title', models.CharField(max_length=300)),
                ('resource_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resource download lead',
                'verbose_name_plural': 'Resource download leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='useful_links', to='a_resources.resourcespage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RunPython(seed_resource_content, migrations.RunPython.noop),
    ]
