# Generated by Django 6.0.3 on 2026-04-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_resources', '0002_resourcedownloadlead_usefullink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreport',
            name='url',
            field=models.URLField(blank=True, help_text='External link to the PDF or document. Leave blank if the report is not yet available — a placeholder will be shown.'),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='year',
            field=models.IntegerField(help_text='Year the report covers, e.g. 2024.'),
        ),
        migrations.AlterField(
            model_name='communitypublication',
            name='category',
            field=models.CharField(help_text='Group label, e.g. "Brochure", "Community Guide", "Newsletter". All entries with the same category are grouped together.', max_length=100),
        ),
        migrations.AlterField(
            model_name='communitypublication',
            name='title',
            field=models.CharField(help_text='Publication title as it should appear to visitors.', max_length=300),
        ),
        migrations.AlterField(
            model_name='communitypublication',
            name='url',
            field=models.URLField(blank=True, help_text='External link to the PDF or document. Leave blank if not yet available.'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='category',
            field=models.CharField(blank=True, help_text='Optional group label, e.g. "Government Services", "Health", "Legal Aid".', max_length=100),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='description',
            field=models.CharField(blank=True, help_text='Brief one-line description of what the link leads to.', max_length=300),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='title',
            field=models.CharField(help_text='Link title as shown to visitors.', max_length=300),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='url',
            field=models.URLField(help_text='Full URL including https://'),
        ),
    ]
