# Generated by Django 6.0.3 on 2026-04-29 12:31

import a_subscribers.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='pending', max_length=20)),
                ('language_preference', models.CharField(choices=[('any', 'Any / No preference'), ('en', 'English'), ('km', 'Khmer (ខ្មែរ)')], default='any', max_length=5)),
                ('source', models.CharField(blank=True, help_text='Where the subscriber signed up, e.g. "footer", "homepage".', max_length=100)),
                ('confirm_token', models.CharField(default=a_subscribers.models._default_token, editable=False, max_length=64, unique=True)),
                ('token_expires_at', models.DateTimeField(default=a_subscribers.models._default_token_expiry)),
                ('unsubscribe_token', models.CharField(default=a_subscribers.models._default_token, editable=False, max_length=64, unique=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
