# Generated by Django 6.0.3 on 2026-05-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_subscribers', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='audience',
            field=models.CharField(choices=[('all', 'All confirmed subscribers'), ('en', 'English (includes "Any" preference)'), ('km', 'Khmer / ខ្មែរ (includes "Any" preference)')], default='all', help_text='Who receives this newsletter. Subscribers with "Any" preference always receive all newsletters.', max_length=5),
        ),
    ]
