# Generated by Django 6.0.3 on 2026-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_impact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactpage',
            name='belief_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='belief_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='belief_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='belief_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='intro_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='newsletter_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='newsletter_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='stat1_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='stat1_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='stat2_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='stat2_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='stat3_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='stat3_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
