# Generated by Django 6.0.3 on 2026-05-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_impact', '0002_impactpage_belief_body_impactpage_belief_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactpage',
            name='programs_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='programs_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
