# Generated by Django 6.0.3 on 2026-05-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_impact', '0003_impactpage_programs_label_impactpage_programs_title'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactpage',
            name='program_1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_1_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_1_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_2_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_3_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
