# Generated by Django 6.0.3 on 2026-05-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_impact', '0004_impactpage_program_1_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactpage',
            name='program_4_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_4_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_4_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_5_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_5_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_5_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_6_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_6_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='impactpage',
            name='program_6_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
