# Generated by Django 6.0.3 on 2026-05-12 09:56

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_impact', '0005_impactpage_program_4_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactpage',
            name='program_1_description',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_1_image',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_1_title',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_2_description',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_2_image',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_2_title',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_3_description',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_3_image',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_3_title',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_4_description',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_4_image',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_4_title',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_5_description',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_5_image',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_5_title',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_6_description',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_6_image',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='program_6_title',
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='belief_body',
            field=models.TextField(blank=True, help_text='Supporting paragraph shown beside the quote.'),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='belief_label',
            field=models.CharField(blank=True, help_text='Eyebrow above the belief heading, e.g. "Our Approach".', max_length=255),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='belief_quote',
            field=models.TextField(blank=True, help_text='Short quote shown in the highlighted card.'),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='belief_title',
            field=models.CharField(blank=True, help_text='Main heading of the belief section.', max_length=255),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Intro paragraph shown under the page title.'),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='newsletter_text',
            field=models.TextField(blank=True, help_text='Short supporting paragraph in the newsletter band.'),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='newsletter_title',
            field=models.CharField(blank=True, help_text='Heading of the dark newsletter call-to-action band.', max_length=255),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='programs_label',
            field=models.CharField(blank=True, help_text='Eyebrow above the programs section heading.', max_length=255),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='programs_title',
            field=models.CharField(blank=True, help_text='Main heading of the programs section.', max_length=255),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='stat1_label',
            field=models.CharField(blank=True, help_text='Label for the first metric, e.g. "Community members supported".', max_length=255),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='stat1_number',
            field=models.CharField(blank=True, help_text='First headline metric, e.g. "1,200".', max_length=50),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Small eyebrow label shown above the hero heading.', max_length=255),
        ),
        migrations.CreateModel(
            name='ImpactProgramEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Short program name shown as the card heading.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='One-to-two sentence description of the program.')),
                ('image', models.ForeignKey(blank=True, help_text='Photo shown on the program card. Landscape orientation works best.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_entries', to='a_impact.impactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
