# Generated by Django 6.0.3 on 2026-05-20 05:58

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_impact', '0006_remove_impactpage_program_1_description_and_more'),
        ('a_programs', '0008_programcategory_locale_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(help_text='e.g. "2025", "2025 Q1", "FY2025".', max_length=100)),
                ('period_type', models.CharField(choices=[('year', 'Year'), ('quarter', 'Quarter'), ('fy', 'Financial Year'), ('custom', 'Custom')], default='year', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text='Short summary of this period. Optional.')),
                ('is_current', models.BooleanField(default=False, help_text='Mark this period as the current one used on the public Impact page. Only one period can be current at a time.')),
                ('public_intro', models.TextField(blank=True, help_text='Intro paragraph shown on the public Impact page when this period is current.')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal-only notes. Never shown publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Impact Reporting Period',
                'verbose_name_plural': 'Impact Reporting Periods',
                'ordering': ['-start_date', '-created_at'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(help_text='What is being measured, e.g. "Families supported".', max_length=200)),
                ('value', models.CharField(help_text='Numeric or short text, e.g. "1,200", "200+", "20 years".', max_length=50)),
                ('unit', models.CharField(blank=True, choices=[('', '(none)'), ('people', 'people'), ('families', 'families'), ('sessions', 'sessions'), ('hours', 'hours'), ('dollars', 'dollars'), ('volunteers', 'volunteers'), ('events', 'events')], help_text='Optional unit shown after the value.', max_length=30)),
                ('category', models.CharField(choices=[('programs', 'Programs'), ('events', 'Events'), ('volunteers', 'Volunteers'), ('donations', 'Donations'), ('community', 'Community Support'), ('settlement', 'Settlement'), ('other', 'Other')], default='programs', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Public explanation of what this metric represents. Shown beneath the metric card on the public page.')),
                ('data_source', models.CharField(blank=True, help_text='Internal source note — never shown publicly. Encouraged for accountability.', max_length=255)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal-only notes. Never shown publicly.')),
                ('display_on_impact_page', models.BooleanField(default=False, help_text='Show this metric on the public Impact page.')),
                ('display_on_homepage', models.BooleanField(default=False, help_text='Show this metric in the homepage impact highlights.')),
                ('chart_enabled', models.BooleanField(default=False, help_text='Include this metric in chart sections (only used when enough comparable metrics exist).')),
                ('chart_group', models.CharField(blank=True, help_text='Optional group name for grouping bars in the chart section.', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('related_program', models.ForeignKey(blank=True, help_text='Optional — link this metric to a specific program page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='a_programs.programpage')),
                ('reporting_period', models.ForeignKey(help_text='Reporting period this metric belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='a_impact.impactreportperiod')),
            ],
            options={
                'verbose_name': 'Impact Metric',
                'verbose_name_plural': 'Impact Metrics',
                'ordering': ['sort_order', '-updated_at'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='ImpactAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('programs', 'Programs'), ('events', 'Events'), ('volunteers', 'Volunteers'), ('donations', 'Donations'), ('community', 'Community Support'), ('settlement', 'Settlement'), ('other', 'Other')], default='other', max_length=30)),
                ('display_on_impact_page', models.BooleanField(default=False, help_text='Show this achievement on the public Impact page.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='a_impact.impactreportperiod')),
            ],
            options={
                'verbose_name': 'Impact Achievement',
                'verbose_name_plural': 'Impact Achievements',
                'ordering': ['sort_order', '-date'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='ImpactStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, help_text='Short summary shown on cards and previews.', max_length=300)),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Full story body.')),
                ('quote', models.TextField(blank=True, help_text='Optional pull-quote highlighted on the public page.')),
                ('category', models.CharField(choices=[('programs', 'Programs'), ('events', 'Events'), ('volunteers', 'Volunteers'), ('donations', 'Donations'), ('community', 'Community Support'), ('settlement', 'Settlement'), ('other', 'Other')], default='programs', max_length=30)),
                ('display_on_impact_page', models.BooleanField(default=False, help_text='Show this story on the public Impact page.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('related_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='a_programs.programpage')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='a_impact.impactreportperiod')),
            ],
            options={
                'verbose_name': 'Impact Story',
                'verbose_name_plural': 'Impact Stories',
                'ordering': ['sort_order', '-updated_at'],
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
