# Generated by Django 6.0.3 on 2026-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_impact', '0007_impactreportperiod_impactmetric_impactachievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactpage',
            name='use_records_system',
            field=models.BooleanField(default=False, help_text='When ticked, the public Impact page renders metrics, stories, and achievements from the new Impact Records system (Impacts → Periods / Metrics / Stories / Achievements). When unticked, the legacy three-stat fields below are used.'),
        ),
    ]
