# Generated by Django 6.0.3 on 2026-05-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_impact', '0009_seed_records_from_legacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactpage',
            name='belief_body',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='belief_label',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='belief_quote',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='belief_title',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='newsletter_text',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='newsletter_title',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='programs_label',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='programs_title',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='stat1_label',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='stat1_number',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='stat2_label',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='stat2_number',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='stat3_label',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='stat3_number',
        ),
        migrations.RemoveField(
            model_name='impactpage',
            name='use_records_system',
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Intro paragraph shown under the page title. Used as a fallback if the current reporting period has no public intro.'),
        ),
        migrations.AlterField(
            model_name='impactpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Small eyebrow label shown above the hero heading. Used as a fallback if the current reporting period has no public intro.', max_length=255),
        ),
        migrations.DeleteModel(
            name='ImpactProgramEntry',
        ),
    ]
