# Generated by Django 6.0.3 on 2026-04-01 17:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='donation_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='donation_cta_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='donation_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='donation_steps',
            field=wagtail.fields.StreamField([('step', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_items',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='support_cards',
            field=wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short label shown in the icon badge, e.g. "01" or "CN".', 'max_length': 3, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('icon_label', 0), ('title', 1), ('description', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='upcoming_events',
            field=wagtail.fields.StreamField([('event', 6)], blank=True, block_lookup={0: ('wagtail.blocks.DateBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Details', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('date', 0), ('title', 1), ('location', 2), ('description', 3), ('cta_text', 4), ('cta_link', 5)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='upcoming_events_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('button', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.URLBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('link', 4)]], {})}),
        ),
    ]
