# Generated by Django 6.0.3 on 2026-04-16 09:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0004_homepage_redesign_fields'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='support_cards',
            field=wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 12, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('icon_label', 0), ('title', 1), ('description', 2)]], {})}),
        ),
        migrations.CreateModel(
            name='GetInvolvedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('volunteer_heading', models.CharField(blank=True, max_length=120)),
                ('volunteer_intro', wagtail.fields.RichTextField(blank=True)),
                ('volunteer_roles', wagtail.fields.StreamField([('role', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "Flexible hours" or "2 days/week"', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional short label or emoji.', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('commitment', 2), ('icon', 3)]], {'label': 'Role'})})),
                ('internship_heading', models.CharField(blank=True, max_length=120)),
                ('internship_intro', wagtail.fields.RichTextField(blank=True)),
                ('internship_roles', wagtail.fields.StreamField([('role', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "Flexible hours" or "2 days/week"', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional short label or emoji.', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('commitment', 2), ('icon', 3)]], {'label': 'Role'})})),
                ('eoi_heading', models.CharField(blank=True, max_length=120)),
                ('eoi_intro', wagtail.fields.RichTextField(blank=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Get Involved Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
