# Generated by Django 6.0.3 on 2026-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0006_data_get_involved'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInvolvedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('interest', models.CharField(max_length=40)),
                ('availability', models.CharField(max_length=40)),
                ('skills', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Get Involved Submission',
                'verbose_name_plural': 'Get Involved Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
