# Generated by Django 6.0.3 on 2026-04-27 04:04

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0007_getinvolvedsubmission'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=80)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('why_title', models.CharField(blank=True, max_length=120)),
                ('why_intro', wagtail.fields.RichTextField(blank=True)),
                ('impact_cards', wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. "Programs", "Outreach", "Cultural Connection".'}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional anchor amount, e.g. "$50 funds program materials for one session."', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('amount_example', 2)]], {})})),
                ('how_title', models.CharField(blank=True, max_length=120)),
                ('how_intro', wagtail.fields.RichTextField(blank=True)),
                ('how_steps', wagtail.fields.StreamField([('step', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})})),
                ('trust_title', models.CharField(blank=True, max_length=120)),
                ('trust_text', wagtail.fields.RichTextField(blank=True)),
                ('abn_number', models.CharField(blank=True, help_text='Australian Business Number, e.g. "12 345 678 901".', max_length=40)),
                ('faq_title', models.CharField(blank=True, max_length=120)),
                ('faq_items', wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})})),
                ('major_gifts_title', models.CharField(blank=True, max_length=120)),
                ('major_gifts_text', wagtail.fields.RichTextField(blank=True)),
                ('major_gifts_email', models.EmailField(blank=True, max_length=254)),
                ('major_gifts_phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Donate Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
