# Generated by Django 6.0.3 on 2026-04-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0009_ensure_donate_page'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Fallback image used in the hero if no photos are added to the Hero Photo Display below. Upload here for a single static image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='primary_cta_link',
            field=models.URLField(blank=True, help_text='Link for the primary button. Use "#donate" to open the donation modal.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='primary_cta_text',
            field=models.CharField(blank=True, help_text='e.g. "Donate Now"', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='secondary_cta_link',
            field=models.URLField(blank=True, help_text='Link for the secondary button, e.g. "/programs/"'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='secondary_cta_text',
            field=models.CharField(blank=True, help_text='e.g. "View Programs"', max_length=80),
        ),
    ]
