# Generated by Django 6.0.3 on 2026-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0010_alter_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='donation_cta_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='primary_cta_link',
            field=models.CharField(blank=True, help_text='Link for the primary button. Use "#donate" to open the donation modal.', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='secondary_cta_link',
            field=models.CharField(blank=True, help_text='Link for the secondary button, e.g. "/programs/"', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='volunteer_cta_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
