# Generated by Django 6.0.3 on 2026-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0011_alter_homepage_donation_cta_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(blank=True, default='CAWC NSW', help_text='Organisation name shown in the footer.', max_length=120)),
                ('phone_number', models.CharField(blank=True, default='+61 2 9727 4336', help_text='Main phone number. Used on the footer, contact page, and click-to-call links.', max_length=40)),
                ('email_address', models.EmailField(blank=True, default='cawcnsw@cambodianwelfare.org.au', help_text='Main contact email. Used on the footer, contact page, and click-to-email links.', max_length=254)),
                ('street_address', models.CharField(blank=True, default='Bonnyrigg Heights Community Centre', help_text='Street address shown on the contact page.', max_length=255)),
                ('suburb', models.CharField(blank=True, default='Bonnyrigg Heights NSW 2177', help_text='Suburb and postcode shown alongside the address.', max_length=120)),
                ('opening_hours', models.CharField(blank=True, default='Mon to Fri, 9:00am to 5:00pm', help_text='Office hours shown on the contact page.', max_length=160)),
                ('abn', models.CharField(blank=True, default='54 003 025 319', help_text='Australian Business Number. Shown in the footer legal bar.', max_length=40)),
            ],
            options={
                'verbose_name': 'Organisation Settings',
            },
        ),
    ]
