# Generated by Django 6.0.3 on 2026-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0012_organisationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='getinvolvedpage',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Optional. When someone submits the Expression of Interest form, a copy is emailed here. Leave blank to use the email from Organisation Settings.', max_length=254),
        ),
    ]
