# Generated by Django 6.0.3 on 2026-05-22 01:16

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0013_getinvolvedpage_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='partners_logos',
            field=wagtail.fields.StreamField([('partner', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Partner or funder organisation name.'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional website link for this partner.', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 1), ('url', 2)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_partners',
            field=models.BooleanField(default=False, help_text='Tick to show the Partners & Supporters section on the homepage.'),
        ),
    ]
