# Generated by Django 6.0.3 on 2026-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_contact', '0004_ensure_contact_page_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Optional. When someone submits the enquiry form, a copy is emailed here. Leave blank to use the email from Organisation Settings.', max_length=254),
        ),
    ]
